# Generated by Django 4.2.7 on 2023-11-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSSs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='acreage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
