# Generated by Django 4.2.7 on 2023-12-01 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASSSs', '0002_house_acreage_house_price_house_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PostingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=1000)),
                ('postingdate', models.DateTimeField(null=True)),
                ('expirationdate', models.DateTimeField(null=True)),
                ('status', models.IntegerField()),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_query_name='posts', to='ASSSs.discount')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_query_name='posts', to='ASSSs.house')),
                ('postingprice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_query_name='posts', to='ASSSs.postingprice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_query_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.CharField(max_length=1000)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_query_name='images', to='ASSSs.house')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followeduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('value', models.CharField(max_length=1000)),
                ('parentcomment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='comments', to='ASSSs.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='comments', to='ASSSs.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='bookings', to='ASSSs.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_query_name='users', to='ASSSs.role'),
        ),
    ]
