# Generated by Django 4.2.7 on 2023-12-01 09:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASSSs', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageURL',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
