# Generated by Django 4.2.7 on 2023-12-26 11:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASSSs', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageURL',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='imageURL'),
        ),
    ]
