# Generated by Django 4.2.7 on 2023-12-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSSs', '0013_alter_image_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
