# Generated by Django 5.0 on 2024-01-10 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSSs', '0019_alter_like_post_alter_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_query_name='bookings', to='ASSSs.post'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_query_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='images', to='ASSSs.house'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='likes', to='ASSSs.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='posts', to='ASSSs.house'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postingprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
