# Generated by Django 5.0 on 2024-01-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSSs', '0021_notice_delete_postingprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
