# Generated by Django 5.0 on 2024-01-23 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSSs', '0023_alter_follow_options_alter_post_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_query_name='posts', to='ASSSs.discount'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postingprice',
            field=models.IntegerField(null=True),
        ),
    ]
