# Generated by Django 5.0 on 2024-01-23 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSSs', '0024_alter_post_discount_alter_post_postingprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='posts', to='ASSSs.discount'),
        ),
    ]
