# Generated by Django 5.0 on 2024-03-02 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSSs', '0025_alter_post_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ASSSs.post'),
        ),
        migrations.AddField(
            model_name='payment',
            name='token_paypal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='payments', to='ASSSs.booking'),
        ),
    ]
